// Code generated by protoc-gen-go-enum. DO NOT EDIT...

package example

// Platform Enum
const (
	Platform_ANDROID int64 = 0 // Android OS
	Platform_IOS     int64 = 1 // iOS
)

var (
	Platform_TXT = map[int64]string{
		Platform_ANDROID: "Android OS",
		Platform_IOS:     "iOS",
	}
)
